#!/bin/sh
# PROVIDE: komga
# REQUIRE: LOGIN
# KEYWORD: shutdown

# shellcheck disable=SC2034
. /etc/rc.subr

name="komga"
rcvar="komga_enable"

# load rc config
load_rc_config $name
: "${komga_enable:=NO}"
: "${komga_user:=komga}"

# load komga plugin config
. /usr/local/etc/komga-plugin.conf
: "${KOMGA_APP_DIR:=/usr/local/komga}"
: "${KOMGA_APP_JAR:=komga-latest.jar}"
: "${KOMGA_JAVA_OPTS:=}"

required_dirs="$KOMGA_APP_DIR"
procname="/usr/local/openjdk11-jre/bin/java"
komga_chdir="$KOMGA_APP_DIR"
komga_env="LANG=en_US.UTF-8"
command="/usr/sbin/daemon"
command_args="-f $procname -jar $KOMGA_JAVA_OPTS $KOMGA_APP_DIR/$KOMGA_APP_JAR"

run_rc_command "$1" 
