#!/bin/sh
# PROVIDE: komga
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="komga"
rcvar="komga_enable"
load_rc_config $name

: ${komga_enable:="NO"}
: ${komga_app_dir:="/usr/local/komga"}
: ${komga_app_jar:="komga.jar"}
: ${komga_java_opts:=""}
: ${komga_user:="komga"}

required_dirs="$komga_app_dir"
procname="/usr/local/openjdk11-jre/bin/java"
komga_chdir="$komga_app_dir"
komga_env="LANG=en_US.UTF-8"
command="/usr/sbin/daemon"
command_args="-f $procname -jar $komga_java_opts $komga_app_dir/$komga_app_jar"

run_rc_command "$1" 
